version: "3.4"

networks:
 app_network:
   name: mcat-ras-network
   driver: bridge

services:
  api:
    container_name: mcat-ras-api
    image: mcat-ras-api
    build:
      target: build
      # target: prod
      context: ./
    volumes:
      - ./:/app
    ports:
      - 5600:5600
    env_file:
      - ./.env
    networks:
      - app_network      

  newman:
    build: ./testing
    image: mcat-ras-newman
    container_name: mcat-ras-newman
    entrypoint: ["/home/testing/entrypoint.sh"]
    depends_on:
      - "api"
    networks:
      - app_network