version: "3.4"

networks:
 app_network:
   name: mcat-ras-network
   driver: bridge

services:
  api:
    container_name: mcat-ras-api
    image: mcat-ras-api
    build:
      target: build
      # target: prod
      context: ./
    volumes:
      - ./:/app
    ports:
      - 5600:5600
    env_file:
      - ./.env
    networks:
      - app_network      

  newman:
    image: postman/newman:alpine
    container_name: mcat-ras-newman
    command:
      run /app/testing/postman_collection.json
    volumes:
      - ./testing:/app/testing
    depends_on:
      - "api"
    networks:
      - app_network  