version: "3.4"

networks:
  app_network:
    name: mcat-ras-network
    driver: bridge

services:
  api:
    container_name: mcat-ras-api
    image: mcat-ras-api
    build:
      # target: build
      # target: local
      target: prod
      context: ./
    volumes:
      - ./:/app
    ports:
      - 5600:5600
    env_file:
      - ./.env
    networks:
      - app_network
  newman:
    image: postman/newman:alpine
    container_name: mcat-ras-newman
    entrypoint: [ "" ]
    command: >
      sh -c "sleep 30s &&
             newman run /app/testing/postman_collection.json
             --env-var url=api:5600
             --env-var bucket=${S3_BUCKET}"
    volumes:
      - ./testing:/app/testing
    depends_on:
      - "api"
    environment:
      - S3_BUCKET=${S3_BUCKET}
    networks:
      - app_network
